sys=../..
<$sys/include/mkfile

TARG=mk.exe
BIN=$sys/bin

CFLAGS=$CFLAGS -O2
LDFLAGS=$LDFLAGS

OFILES=\
	9pm.$O\
	arc.$O\
	archive.$O\
	bufblock.$O\
	dir.$O\
	env.$O\
	file.$O\
	graph.$O\
	job.$O\
	lex.$O\
	main.$O\
	match.$O\
	mk.$O\
	parse.$O\
	rc.$O\
	recipe.$O\
	rule.$O\
	run.$O\
	shprint.$O\
	symtab.$O\
	var.$O\
	varsub.$O\
	word.$O\

HFILES=\
	fns.h\
	mk.h\

<$sys/include/mkone

