sys=../..
<$sys/include/mkfile

CFLAGS=$CFLAGS
LDFLAGS=$LDFLAGS -subsystem:windows

TARG=9term.exe
OFILES=9term.$O\

LIBS=\
	9pm.lib\
	c.lib\
	libg.lib\
	frame.lib\

BIN=$sys/bin
<$sys/include/mkone

